/* This file is generated by scripts/generate-client-contracts/generate.py. */
/* Do not edit it by hand. */

export type OAuthScope = "terminal.read" | "terminal.write" | "computers.read" | "computers.write"
export type OAuthDeviceTokenErrorCode = "authorization_pending" | "slow_down" | "access_denied" | "expired_token"
export type TerminalAction = "split_left_right" | "split_top_bottom" | "new_window" | "select_left" | "select_right" | "select_up" | "select_down" | "toggle_zoom" | "copy_mode" | "close_pane"
export type TerminalCloseReason = "client_closed" | "replaced" | "grace_expired" | "stream_gap" | "instance_offline" | "internal_error"
export type AgentInput = UserMessageInput | WatchTriggeredInput | TimerTriggeredInput | PermissionResolvedInput | SystemNotificationInput
export type AgentEvent = RunStartedEvent | MessageDeltaEvent | MessageCompletedEvent | ToolStartedEvent | ToolCompletedEvent | PermissionRequestedEvent | RunCompletedEvent | RunFailedEvent | BackendStateChangedEvent
export const PROTOCOL_VERSION = 1 as const

export interface ErrorDetail {
  code: string
  message: string
  request_id: string
}

export interface ErrorEnvelope {
  error: ErrorDetail
}

export interface BrowserSessionResponse {
  authenticated: boolean
  expires_at: string
}

export interface BrowserSessionDeleteResponse {
  ok: boolean
}

export interface BrowserSessionChallengeResponse {
  status: "totp_required"
  challenge_id: string
  expires_at: string
}

export interface TotpStatusResponse {
  configured: boolean
  enabled: boolean
  available: boolean
}

export interface TotpSetupResponse {
  setup_id: string
  provisioning_uri: string
  setup_key: string
  expires_at: string
}

export interface OAuthPublicJwk {
  kty: "EC"
  crv: "P-256"
  alg: "ES256"
  x: string
  y: string
}

export interface OAuthMetadataResponse {
  issuer: string
  authorization_endpoint: string
  token_endpoint: string
  revocation_endpoint: string
  device_authorization_endpoint: string
  device_verification_uri: string
  response_types_supported: "code"[]
  grant_types_supported: ("authorization_code" | "refresh_token" | "urn:ietf:params:oauth:grant-type:device_code")[]
  code_challenge_methods_supported: "S256"[]
  dpop_signing_alg_values_supported: "ES256"[]
  scopes_supported: OAuthScope[]
}

export interface OAuthAuthorizationRequest {
  response_type: "code"
  client_name: string
  platform: string
  client_version: string | null
  redirect_uri: string
  state: string
  code_challenge: string
  code_challenge_method: "S256"
  dpop_jkt: string
  public_jwk: OAuthPublicJwk
  scopes: OAuthScope[]
}

export interface OAuthDeviceCodeRequest {
  client_name: string
  platform: string
  client_version: string | null
  code_challenge: string
  code_challenge_method: "S256"
  dpop_jkt: string
  public_jwk: OAuthPublicJwk
  scopes: OAuthScope[]
}

export interface OAuthDeviceCodeResponse {
  device_code: string
  user_code: string
  verification_uri: string
  verification_uri_complete: string
  expires_in: number
  interval: number
}

export interface OAuthDeviceTokenError {
  error: OAuthDeviceTokenErrorCode
}

export interface OAuthAuthorizationPreviewResponse {
  transaction_id: string
  issuer: string
  client_name: string
  platform: string
  client_version: string | null
  key_fingerprint: string
  scopes: OAuthScope[]
  redirect_uri: string
  totp_required: boolean
  expires_at: string
}

export interface OAuthAuthorizationDecisionResponse {
  status: "approved" | "denied"
  callback_uri: string
}

export interface OAuthTokenResponse {
  token_type: "DPoP"
  access_token: string
  expires_in: number
  refresh_token: string
  scopes: OAuthScope[]
}

export interface OAuthRevokeResponse {
  ok: boolean
}

export interface CliTokenResponse {
  token_type: "Bearer"
  access_token: string
  expires_in: number
  scopes: OAuthScope[]
}

export interface NativeClientResponse {
  client_id: string
  display_name: string
  platform: string
  client_version: string | null
  key_thumbprint: string
  scopes: OAuthScope[]
  created_at: string
  last_used_at: string | null
  revoked_at: string | null
}

export interface NativeClientListResponse {
  clients: NativeClientResponse[]
}

export interface NativeClientUpdateRequest {
  display_name: string
}

export interface NativeClientDeleteResponse {
  ok: boolean
}

export interface DashboardMetrics {
  online_terms: number
  total_terms: number
  active_panes: number
  interactions_24h: number
  computers: number
}

export interface TermSummary {
  instance_id: string
  name: string
  online: boolean
  window_count: number
  pane_count: number
  active_pane_count: number
  current_command: string | null
  last_seen_at: string | null
}

export interface ComputerSummary {
  installation_id: string
  hostname: string | null
  display_name: string
  platform: string | null
  client_version: string | null
  registered_at: string | null
  last_seen_at: string | null
  online: boolean
  terms: TermSummary[]
}

export interface ComputerListResponse {
  computers: ComputerSummary[]
}

export interface DashboardResponse {
  metrics: DashboardMetrics
  computers: ComputerSummary[]
}

export interface EnrollmentCreateResponse {
  token: string
  expires_at: string
  server_url: string
  login_command: string
}

export interface PaneSnapshot {
  pane_id: string
  window_id: string
  index: number
  title: string
  width: number
  height: number
  left: number
  top: number
  current_command: string | null
  active: boolean
  dead: boolean
}

export interface WindowSnapshot {
  window_id: string
  index: number
  name: string
  active: boolean
  panes: PaneSnapshot[]
}

export interface TopologySnapshot {
  session_id: string
  session_name: string
  revision: number
  windows: WindowSnapshot[]
}

export interface TopologyResponse {
  instance_id: string
  topology: TopologySnapshot
}

export interface TerminalBinding {
  action: TerminalAction
  key: string | null
  tooltip: string
}

export interface TerminalReadyFrame {
  type: "terminal.ready"
  terminal_id: string
  stream_id: string
  rows: number
  cols: number
}

export interface TerminalSizeFrame {
  type: "terminal.size"
  terminal_id: string
  rows: number
  cols: number
}

export interface TerminalBindingSnapshotFrame {
  type: "terminal.binding_snapshot"
  terminal_id: string
  prefix: string
  prefix2: string | null
  bindings: TerminalBinding[]
}

export interface TerminalErrorFrame {
  type: "terminal.error"
  terminal_id: string
  code: string
  message: string
}

export interface TerminalClosedFrame {
  type: "terminal.closed"
  terminal_id: string
  reason: TerminalCloseReason
}

export interface TerminalActionResultFrame {
  type: "terminal.action_result"
  terminal_id: string
  action_id: string
  ok: boolean
  error_code: string | null
}

export interface AgentCapabilitiesResponse {
  agent_broker_enabled: boolean
  state: "starting" | "ready" | "degraded" | "disabled"
  reason_code: "recovery_failed" | null
  delegated_write_grants_enabled: boolean
}

export interface CleanupPendingResponse {
  cleanup_job_id: string
  state: "deletion_pending"
  status_url: string
}

export interface CleanupReceiptResponse {
  receipt_id: string
  artifact_kind: string
  state: "pending" | "confirmed" | "not_applicable" | "dead_letter"
  attempt_count: number
  next_attempt_at: string | null
  reason_code: string | null
}

export interface CleanupJobResponse {
  cleanup_job_id: string
  target_kind: string
  state: "pending" | "completed" | "dead_letter"
  receipts: CleanupReceiptResponse[]
}

export interface AgentConversationCreateRequest {
  binding_id: string
  title: string | null
}

export interface AgentConversationUpdateRequest {
  title: string
}

export interface AgentConversationResponse {
  conversation_id: string
  binding_id: string
  title: string | null
  status: string
  created_at: string
  updated_at: string
}

export interface AgentConversationListResponse {
  conversations: AgentConversationResponse[]
}

export interface AgentConversationBindingInfo {
  binding_id: string
  profile_id: string
  term_id: string
  status: string
}

export interface AgentConversationDetailResponse {
  conversation_id: string
  binding_id: string
  title: string | null
  status: string
  created_at: string
  updated_at: string
  binding: AgentConversationBindingInfo
}

export interface AgentMessageResponse {
  message_id: string
  conversation_id: string
  run_id: string | null
  role: string
  kind: string
  assembly_revision: number
  is_final: boolean
  body_digest: string
  body: string | null
  created_at: string
}

export interface AgentMessageListResponse {
  messages: AgentMessageResponse[]
}

export interface AgentSubmitMessageRequest {
  text: string
}

export interface AgentSubmitMessageResponse {
  message_id: string
  conversation_id: string
  admission_seq: number
  idempotency_key: string
  delivery_state: string
  submission_state: string
}

export interface AgentCancelRequest {
  reason: string | null
}

export interface AgentCancelResponse {
  outcome: string
  run_state: string
}

export interface AgentEventResponse {
  event_id: string
  conversation_id: string
  run_id: string | null
  event_kind: string
  database_seq: number
  payload_digest: string
  ephemeral: boolean
  created_at: string
}

export interface AgentEventListResponse {
  events: AgentEventResponse[]
  next_cursor: number | null
}

export interface ApprovalResponse {
  approval_id: string
  binding_id: string
  conversation_id: string
  run_id: string | null
  tool_call_id: string
  canonical_hash: string
  state: string
  expires_at: string
  decided_at: string | null
  decision: string | null
  auth_epoch: number
  created_at: string
  pane_id: string | null
  operation: string | null
  intent_summary: string | null
}

export interface ApprovalBindingInfo {
  binding_id: string
  profile_id: string
  term_id: string
  status: string
}

export interface ApprovalDetailResponse {
  approval_id: string
  binding_id: string
  conversation_id: string
  run_id: string | null
  tool_call_id: string
  canonical_hash: string
  state: string
  expires_at: string
  decided_at: string | null
  decision: string | null
  auth_epoch: number
  created_at: string
  pane_id: string | null
  operation: string | null
  intent_summary: string | null
  binding: ApprovalBindingInfo
}

export interface ApprovalListResponse {
  approvals: ApprovalResponse[]
}

export interface ApprovalDecisionRequest {
  decision: "approve" | "deny"
}

export interface AgentProfileCreateRequest {
  display_name: string
  backend_kind: string
  config: string
}

export interface AgentProfileUpdateRequest {
  display_name: string | null
  config: string | null
}

export interface AgentProfileResponse {
  profile_id: string
  display_name: string
  backend_kind: string
  config: string
  created_at: string
  updated_at: string
}

export interface AgentProfileListResponse {
  profiles: AgentProfileResponse[]
}

export interface AgentBindingCreateRequest {
  profile_id: string
  term_id: string
}

export interface AgentBindingUpdateRequest {
  status: "disabled" | "revoked" | null
}

export interface AgentBindingResponse {
  binding_id: string
  profile_id: string
  term_id: string
  status: string
  runtime_ref: string | null
  runtime_epoch: number | null
  capability_ref: string | null
  created_at: string
  updated_at: string
}

export interface AgentBindingListResponse {
  bindings: AgentBindingResponse[]
}

export interface AgentBindingDetailResponse {
  binding_id: string
  profile_id: string
  term_id: string
  status: string
  config_revision: number
  runtime_ref: string | null
  runtime_epoch: number | null
  capability_ref: string | null
  profile: AgentSetupProfileSummary | null
  runtime: AgentRuntimeStateResponse | null
  pane_policy: AgentPanePolicyResponse
  disclosure: AgentProviderDisclosureResponse | null
}

export interface AgentBindingRuntimeUpdateRequest {
  runtime_ref: string
  capability_ref: string
  expected_revision: number
}

export interface AgentDisclosureAcceptRequest {
  disclosure_fingerprint: string
  accepted: true
}

export interface AgentPanePolicyReplaceRequest {
  pane_ids: string[]
  topology_revision: number
  expected_revision: number | null
}

export interface AgentPanePolicyResponse {
  binding_id: string
  pane_ids: string[]
  topology_revision: number | null
}

export interface AgentProviderDisclosureResponse {
  binding_id: string | null
  disclosure_fingerprint: string
  provider_id: string
  model_id: string
  endpoint_origin: string
  region: string
  retention_terms: string
  retention_version: string
  no_training: boolean
  policy_version: string
  credential_source: string | null
  accepted: boolean
  accepted_at: string | null
  accepted_auth_epoch: number | null
}

export interface AgentRuntimeStateResponse {
  readiness: string
  reason_code: string | null
  config_revision: number
  applied_revision: number | null
  runtime_epoch: number | null
  provider_readiness: string
  observed_runtime_ref: string | null
  observed_capability_ref: string | null
  provider_reason_code: string | null
}

export interface AgentSetupProfileSummary {
  profile_id: string
  display_name: string
  backend_kind: string
  provider_id: string | null
  model_id: string | null
}

export interface AgentSetupRequest {
  term_id: string
  profile_id: string | null
  profile_display_name: string | null
  pane_ids: string[]
  topology_revision: number
  disclosure_fingerprint: string
  accepted: true
  idempotency_key: string
}

export interface AgentSetupResponse {
  state: "unconfigured" | "deployment_required" | "activating" | "ready" | "unavailable"
  term_id: string
  binding_id: string | null
  profile: AgentSetupProfileSummary | null
  profiles: AgentSetupProfileSummary[]
  token: AgentSetupTokenSummary
  runtime: AgentRuntimeStateResponse | null
  pane_policy: AgentPanePolicyResponse | null
  disclosure: AgentProviderDisclosureResponse | null
  topology_revision: number | null
  reason_code: string | null
}

export interface AgentSetupTokenSummary {
  installed: boolean
  expires_at: string | null
}

export interface AgentTokenCreateRequest {
  binding_id: string
  scopes: string[]
  expires_at: string
}

export interface AgentTokenCreatedResponse {
  token_id: string
  binding_id: string
  scopes: string[]
  expires_at: string
  raw_token: string
  created_at: string
}

export interface AgentTokenResponse {
  token_id: string
  binding_id: string
  scopes: string[]
  expires_at: string
  revoked_at: string | null
  created_at: string
}

export interface AgentTokenListResponse {
  tokens: AgentTokenResponse[]
}

export interface UserMessagePayload {
  text: string
}

export interface WatchTriggeredPayload {
  watch_id: string
  watch_generation: number
  trigger_event_id: string
  continuation: string | null
  observation_ref: string | null
}

export interface TimerTriggeredPayload {
  timer_id: string
  scheduled_for: string
}

export interface PermissionResolvedPayload {
  approval_request_id: string
  decision: "approved" | "denied" | "expired" | "revoked" | "unknown"
  resolved_by_actor_id: string | null
  resolved_at: string
}

export interface SystemNotificationPayload {
  notification_type: string
  text: string
  event_ref: string | null
}

export interface UserMessageInput {
  input_id: string
  conversation_id: string
  actor_id: string
  actor_kind: "user_session" | "client" | "watch_engine" | "timer" | "backend" | "system"
  auth_epoch: number | null
  admission_seq: number
  idempotency_key: string
  source: "user" | "system" | "backend"
  causation_id: string
  correlation_id: string
  created_at: string
  delivery_state: "pending" | "delivered" | "failed" | "dead_lettered"
  attempt_count: number
  kind: "user_message"
  payload: UserMessagePayload
}

export interface WatchTriggeredInput {
  input_id: string
  conversation_id: string
  actor_id: string
  actor_kind: "user_session" | "client" | "watch_engine" | "timer" | "backend" | "system"
  auth_epoch: number | null
  admission_seq: number
  idempotency_key: string
  source: "user" | "system" | "backend"
  causation_id: string
  correlation_id: string
  created_at: string
  delivery_state: "pending" | "delivered" | "failed" | "dead_lettered"
  attempt_count: number
  kind: "watch_triggered"
  payload: WatchTriggeredPayload
}

export interface TimerTriggeredInput {
  input_id: string
  conversation_id: string
  actor_id: string
  actor_kind: "user_session" | "client" | "watch_engine" | "timer" | "backend" | "system"
  auth_epoch: number | null
  admission_seq: number
  idempotency_key: string
  source: "user" | "system" | "backend"
  causation_id: string
  correlation_id: string
  created_at: string
  delivery_state: "pending" | "delivered" | "failed" | "dead_lettered"
  attempt_count: number
  kind: "timer_triggered"
  payload: TimerTriggeredPayload
}

export interface PermissionResolvedInput {
  input_id: string
  conversation_id: string
  actor_id: string
  actor_kind: "user_session" | "client" | "watch_engine" | "timer" | "backend" | "system"
  auth_epoch: number | null
  admission_seq: number
  idempotency_key: string
  source: "user" | "system" | "backend"
  causation_id: string
  correlation_id: string
  created_at: string
  delivery_state: "pending" | "delivered" | "failed" | "dead_lettered"
  attempt_count: number
  kind: "permission_resolved"
  payload: PermissionResolvedPayload
}

export interface SystemNotificationInput {
  input_id: string
  conversation_id: string
  actor_id: string
  actor_kind: "user_session" | "client" | "watch_engine" | "timer" | "backend" | "system"
  auth_epoch: number | null
  admission_seq: number
  idempotency_key: string
  source: "user" | "system" | "backend"
  causation_id: string
  correlation_id: string
  created_at: string
  delivery_state: "pending" | "delivered" | "failed" | "dead_lettered"
  attempt_count: number
  kind: "system_notification"
  payload: SystemNotificationPayload
}

export interface RunStartedPayload {
  input_id: string | null
}

export interface MessageDeltaPayload {
  message_id: string
  part_id: string | null
  assembly_revision: number
  text: string | null
  ephemeral: boolean
}

export interface MessageCompletedPayload {
  message_id: string
  assembly_revision: number
  final: boolean
}

export interface ToolStartedPayload {
  tool_name: string
  tool_call_id: string
}

export interface ToolCompletedPayload {
  tool_name: string
  tool_call_id: string
  status: "success" | "error" | "cancelled" | "unknown"
  input_bytes: number
  output_bytes: number
  input_hash: string | null
  output_hash: string | null
  truncated: boolean
  error_code: string | null
  error_message: string | null
}

export interface PermissionRequestedPayload {
  approval_request_id: string
  tool_name: string | null
  evidence: string | null
  expires_at: string | null
}

export interface RunCompletedPayload {
  input_id: string | null
}

export interface RunFailedPayload {
  error_code: string
  error_message: string | null
  retryable: boolean
}

export interface BackendStateChangedPayload {
  state: "connecting" | "ready" | "unavailable" | "context_lost" | "reconciling" | "closed"
  epoch: number
}

export interface RunStartedEvent {
  event_id: string
  conversation_id: string
  run_id: string | null
  dedup_key: string
  database_seq: number
  created_at: string
  kind: "run_started"
  payload: RunStartedPayload
}

export interface MessageDeltaEvent {
  event_id: string
  conversation_id: string
  run_id: string | null
  dedup_key: string
  database_seq: number
  created_at: string
  kind: "message_delta"
  payload: MessageDeltaPayload
}

export interface MessageCompletedEvent {
  event_id: string
  conversation_id: string
  run_id: string | null
  dedup_key: string
  database_seq: number
  created_at: string
  kind: "message_completed"
  payload: MessageCompletedPayload
}

export interface ToolStartedEvent {
  event_id: string
  conversation_id: string
  run_id: string | null
  dedup_key: string
  database_seq: number
  created_at: string
  kind: "tool_started"
  payload: ToolStartedPayload
}

export interface ToolCompletedEvent {
  event_id: string
  conversation_id: string
  run_id: string | null
  dedup_key: string
  database_seq: number
  created_at: string
  kind: "tool_completed"
  payload: ToolCompletedPayload
}

export interface PermissionRequestedEvent {
  event_id: string
  conversation_id: string
  run_id: string | null
  dedup_key: string
  database_seq: number
  created_at: string
  kind: "permission_requested"
  payload: PermissionRequestedPayload
}

export interface RunCompletedEvent {
  event_id: string
  conversation_id: string
  run_id: string | null
  dedup_key: string
  database_seq: number
  created_at: string
  kind: "run_completed"
  payload: RunCompletedPayload
}

export interface RunFailedEvent {
  event_id: string
  conversation_id: string
  run_id: string | null
  dedup_key: string
  database_seq: number
  created_at: string
  kind: "run_failed"
  payload: RunFailedPayload
}

export interface BackendStateChangedEvent {
  event_id: string
  conversation_id: string
  run_id: string | null
  dedup_key: string
  database_seq: number
  created_at: string
  kind: "backend_state_changed"
  payload: BackendStateChangedPayload
}
