/* This file is generated by scripts/generate-client-contracts/generate.py. */
/* Do not edit it by hand. */

export type TerminalAction = "split_left_right" | "split_top_bottom" | "new_window" | "select_left" | "select_right" | "select_up" | "select_down" | "toggle_zoom" | "copy_mode" | "close_pane"
export type TerminalCloseReason = "client_closed" | "replaced" | "grace_expired" | "stream_gap" | "instance_offline" | "internal_error"

export interface BrowserSessionResponse {
  authenticated: boolean
  expires_at: string
}

export interface DashboardMetrics {
  online_terms: number
  total_terms: number
  active_panes: number
  interactions_24h: number
  computers: number
}

export interface TermSummary {
  instance_id: string
  name: string
  online: boolean
  window_count: number
  pane_count: number
  active_pane_count: number
  current_command: string | null
  last_seen_at: string | null
}

export interface ComputerSummary {
  installation_id: string
  hostname: string | null
  display_name: string
  platform: string | null
  client_version: string | null
  registered_at: string | null
  last_seen_at: string | null
  online: boolean
  terms: TermSummary[]
}

export interface ComputerListResponse {
  computers: ComputerSummary[]
}

export interface DashboardResponse {
  metrics: DashboardMetrics
  computers: ComputerSummary[]
}

export interface EnrollmentCreateResponse {
  token: string
  expires_at: string
}

export interface PaneSnapshot {
  pane_id: string
  window_id: string
  index: number
  title: string
  width: number
  height: number
  left: number
  top: number
  current_command: string | null
  active: boolean
  dead: boolean
}

export interface WindowSnapshot {
  window_id: string
  index: number
  name: string
  active: boolean
  panes: PaneSnapshot[]
}

export interface TopologySnapshot {
  session_id: string
  session_name: string
  revision: number
  windows: WindowSnapshot[]
}

export interface TopologyResponse {
  instance_id: string
  topology: TopologySnapshot
}

export interface TerminalBinding {
  action: TerminalAction
  key: string | null
  tooltip: string
}

export interface TerminalReadyFrame {
  type: "terminal.ready"
  terminal_id: string
  stream_id: string
  rows: number
  cols: number
}

export interface TerminalSizeFrame {
  type: "terminal.size"
  terminal_id: string
  rows: number
  cols: number
}

export interface TerminalBindingSnapshotFrame {
  type: "terminal.binding_snapshot"
  terminal_id: string
  prefix: string
  prefix2: string | null
  bindings: TerminalBinding[]
}

export interface TerminalErrorFrame {
  type: "terminal.error"
  terminal_id: string
  code: string
  message: string
}

export interface TerminalClosedFrame {
  type: "terminal.closed"
  terminal_id: string
  reason: TerminalCloseReason
}

export interface TerminalActionResultFrame {
  type: "terminal.action_result"
  terminal_id: string
  action_id: string
  ok: boolean
  error_code: string | null
}
