/* This file is generated by scripts/generate-client-contracts/generate.py. */
/* Do not edit it by hand. */

export type OAuthScope = "terminal.read" | "terminal.write" | "computers.read" | "computers.write"
export type OAuthDeviceTokenErrorCode = "authorization_pending" | "slow_down" | "access_denied" | "expired_token"
export type TerminalAction = "split_left_right" | "split_top_bottom" | "new_window" | "select_left" | "select_right" | "select_up" | "select_down" | "toggle_zoom" | "copy_mode" | "close_pane"
export type TerminalCloseReason = "client_closed" | "replaced" | "grace_expired" | "stream_gap" | "instance_offline" | "internal_error"
export const PROTOCOL_VERSION = 1 as const

export interface ErrorDetail {
  code: string
  message: string
  request_id: string
}

export interface ErrorEnvelope {
  error: ErrorDetail
}

export interface BrowserSessionResponse {
  authenticated: boolean
  expires_at: string
}

export interface BrowserSessionDeleteResponse {
  ok: boolean
}

export interface BrowserSessionChallengeResponse {
  status: "totp_required"
  challenge_id: string
  expires_at: string
}

export interface TotpStatusResponse {
  configured: boolean
  enabled: boolean
  available: boolean
}

export interface TotpSetupResponse {
  setup_id: string
  provisioning_uri: string
  setup_key: string
  expires_at: string
}

export interface OAuthPublicJwk {
  kty: "EC"
  crv: "P-256"
  alg: "ES256"
  x: string
  y: string
}

export interface OAuthMetadataResponse {
  issuer: string
  authorization_endpoint: string
  token_endpoint: string
  revocation_endpoint: string
  device_authorization_endpoint: string
  device_verification_uri: string
  response_types_supported: "code"[]
  grant_types_supported: ("authorization_code" | "refresh_token")[]
  code_challenge_methods_supported: "S256"[]
  dpop_signing_alg_values_supported: "ES256"[]
  scopes_supported: OAuthScope[]
}

export interface OAuthAuthorizationRequest {
  response_type: "code"
  client_name: string
  platform: string
  client_version: string | null
  redirect_uri: string
  state: string
  code_challenge: string
  code_challenge_method: "S256"
  dpop_jkt: string
  public_jwk: OAuthPublicJwk
  scopes: OAuthScope[]
}

export interface OAuthDeviceCodeRequest {
  client_name: string
  platform: string
  client_version: string | null
  code_challenge: string
  code_challenge_method: "S256"
  dpop_jkt: string
  public_jwk: OAuthPublicJwk
  scopes: OAuthScope[]
}

export interface OAuthDeviceCodeResponse {
  device_code: string
  user_code: string
  verification_uri: string
  verification_uri_complete: string
  expires_in: number
  interval: number
}

export interface OAuthDeviceTokenError {
  error: OAuthDeviceTokenErrorCode
}

export interface OAuthAuthorizationPreviewResponse {
  transaction_id: string
  issuer: string
  client_name: string
  platform: string
  client_version: string | null
  key_fingerprint: string
  scopes: OAuthScope[]
  redirect_uri: string
  totp_required: boolean
  expires_at: string
}

export interface OAuthAuthorizationDecisionResponse {
  status: "approved" | "denied"
  callback_uri: string
}

export interface OAuthTokenResponse {
  token_type: "DPoP"
  access_token: string
  expires_in: number
  refresh_token: string
  scopes: OAuthScope[]
}

export interface OAuthRevokeResponse {
  ok: boolean
}

export interface CliTokenResponse {
  token_type: "Bearer"
  access_token: string
  expires_in: number
  scopes: OAuthScope[]
}

export interface NativeClientResponse {
  client_id: string
  display_name: string
  platform: string
  client_version: string | null
  key_thumbprint: string
  scopes: OAuthScope[]
  created_at: string
  last_used_at: string | null
  revoked_at: string | null
}

export interface NativeClientListResponse {
  clients: NativeClientResponse[]
}

export interface NativeClientUpdateRequest {
  display_name: string
}

export interface NativeClientDeleteResponse {
  ok: boolean
}

export interface DashboardMetrics {
  online_terms: number
  total_terms: number
  active_panes: number
  interactions_24h: number
  computers: number
}

export interface TermSummary {
  instance_id: string
  name: string
  online: boolean
  window_count: number
  pane_count: number
  active_pane_count: number
  current_command: string | null
  last_seen_at: string | null
}

export interface ComputerSummary {
  installation_id: string
  hostname: string | null
  display_name: string
  platform: string | null
  client_version: string | null
  registered_at: string | null
  last_seen_at: string | null
  online: boolean
  terms: TermSummary[]
}

export interface ComputerListResponse {
  computers: ComputerSummary[]
}

export interface DashboardResponse {
  metrics: DashboardMetrics
  computers: ComputerSummary[]
}

export interface EnrollmentCreateResponse {
  token: string
  expires_at: string
  server_url: string
  login_command: string
}

export interface PaneSnapshot {
  pane_id: string
  window_id: string
  index: number
  title: string
  width: number
  height: number
  left: number
  top: number
  current_command: string | null
  active: boolean
  dead: boolean
}

export interface WindowSnapshot {
  window_id: string
  index: number
  name: string
  active: boolean
  panes: PaneSnapshot[]
}

export interface TopologySnapshot {
  session_id: string
  session_name: string
  revision: number
  windows: WindowSnapshot[]
}

export interface TopologyResponse {
  instance_id: string
  topology: TopologySnapshot
}

export interface TerminalBinding {
  action: TerminalAction
  key: string | null
  tooltip: string
}

export interface TerminalReadyFrame {
  type: "terminal.ready"
  terminal_id: string
  stream_id: string
  rows: number
  cols: number
}

export interface TerminalSizeFrame {
  type: "terminal.size"
  terminal_id: string
  rows: number
  cols: number
}

export interface TerminalBindingSnapshotFrame {
  type: "terminal.binding_snapshot"
  terminal_id: string
  prefix: string
  prefix2: string | null
  bindings: TerminalBinding[]
}

export interface TerminalErrorFrame {
  type: "terminal.error"
  terminal_id: string
  code: string
  message: string
}

export interface TerminalClosedFrame {
  type: "terminal.closed"
  terminal_id: string
  reason: TerminalCloseReason
}

export interface TerminalActionResultFrame {
  type: "terminal.action_result"
  terminal_id: string
  action_id: string
  ok: boolean
  error_code: string | null
}
