#!/usr/bin/env python3
"""Render the browser-visible TypeScript contract from public Pydantic models."""

from __future__ import annotations

import argparse
import json
import sys
import types
from datetime import datetime
from pathlib import Path
from typing import Annotated, Literal, TypeAliasType, Union, get_args, get_origin
from uuid import UUID

from pydantic import BaseModel
from termflow_protocol import (
    BrowserSessionResponse,
    ComputerListResponse,
    ComputerSummary,
    DashboardMetrics,
    DashboardResponse,
    EnrollmentCreateResponse,
    PaneSnapshot,
    TerminalAction,
    TerminalActionResultFrame,
    TerminalBinding,
    TerminalBindingSnapshotFrame,
    TerminalClosedFrame,
    TerminalCloseReason,
    TerminalErrorFrame,
    TerminalReadyFrame,
    TerminalSizeFrame,
    TermSummary,
    TopologyResponse,
    TopologySnapshot,
    WindowSnapshot,
)

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = ROOT / "packages/client-contracts/src/generated.ts"

TYPE_ALIASES: tuple[TypeAliasType, ...] = (TerminalAction, TerminalCloseReason)
MODELS: tuple[type[BaseModel], ...] = (
    BrowserSessionResponse,
    DashboardMetrics,
    TermSummary,
    ComputerSummary,
    ComputerListResponse,
    DashboardResponse,
    EnrollmentCreateResponse,
    PaneSnapshot,
    WindowSnapshot,
    TopologySnapshot,
    TopologyResponse,
    TerminalBinding,
    TerminalReadyFrame,
    TerminalSizeFrame,
    TerminalBindingSnapshotFrame,
    TerminalErrorFrame,
    TerminalClosedFrame,
    TerminalActionResultFrame,
)
EXPORTED_ALIAS_IDS = {id(alias): alias.__name__ for alias in TYPE_ALIASES}


def _literal(value: object) -> str:
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if value is True:
        return "true"
    if value is False:
        return "false"
    if value is None:
        return "null"
    if isinstance(value, (int, float)):
        return str(value)
    raise TypeError(f"unsupported Literal value: {value!r}")


def _render_type(annotation: object) -> str:
    exported_alias = EXPORTED_ALIAS_IDS.get(id(annotation))
    if exported_alias is not None:
        return exported_alias
    if isinstance(annotation, TypeAliasType):
        return _render_type(annotation.__value__)
    if annotation in (str, UUID, datetime):
        return "string"
    if annotation in (int, float):
        return "number"
    if annotation is bool:
        return "boolean"
    if annotation is type(None):
        return "null"

    origin = get_origin(annotation)
    arguments = get_args(annotation)
    if origin is Annotated:
        return _render_type(arguments[0])
    if origin is Literal:
        return " | ".join(_literal(value) for value in arguments)
    if origin is list:
        return f"{_render_type(arguments[0])}[]"
    if origin in (types.UnionType, Union):
        return " | ".join(_render_type(argument) for argument in arguments)
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return annotation.__name__
    raise TypeError(f"unsupported contract annotation: {annotation!r}")


def render() -> str:
    lines = [
        "/* This file is generated by scripts/generate-client-contracts/generate.py. */",
        "/* Do not edit it by hand. */",
        "",
    ]
    for alias in TYPE_ALIASES:
        lines.append(f"export type {alias.__name__} = {_render_type(alias.__value__)}")
    lines.append("")
    for model in MODELS:
        lines.append(f"export interface {model.__name__} {{")
        for name, field in model.model_fields.items():
            lines.append(f"  {name}: {_render_type(field.annotation)}")
        lines.extend(("}", ""))
    return "\n".join(lines)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> int:
    arguments = _parse_args()
    output: Path = arguments.output
    rendered = render()
    if arguments.check:
        if not output.is_file() or output.read_text() != rendered:
            print(f"generated client contract is stale: {output}", file=sys.stderr)
            return 1
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
