FROM rust:1.97-bookworm

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install --yes --no-install-recommends \
        libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf \
        libgtk-3-dev libayatana-appindicator3-dev libssl-dev libxdo-dev \
        libdbus-1-dev libjavascriptcoregtk-4.1-dev libsoup-3.0-dev \
        pkg-config ca-certificates \
    && rm -rf /var/lib/apt/lists/* \
    && rustup component add rustfmt clippy
