#!/usr/bin/env python3
"""Inject the audio permissions required by in-WebView voice capture into the generated
Tauri Android manifest (idempotent, fail-loud).

The Tauri Android configuration has no permissions key, so the manifest generated by
``tauri android init`` must be patched after generation. ``gen/`` is gitignored and
regenerated on every CI run, hence this script is wired into CI right after
``android init --ci`` and documented for local development.

Exits non-zero when the manifest is missing or malformed so a broken patch pipeline
blocks the build instead of silently shipping without microphone permissions.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

DEFAULT_MANIFEST = Path("apps/clients/tauri/src-tauri/gen/android/app/src/main/AndroidManifest.xml")

PERMISSIONS = (
    "android.permission.RECORD_AUDIO",
    "android.permission.MODIFY_AUDIO_SETTINGS",
)

_MANIFEST_OPEN_TAG = re.compile(r"<manifest\b[^>]*>", re.IGNORECASE)
_DECLARED_PERMISSION = re.compile(
    r"<uses-permission\b[^>]*android:name=\"([^\"]+)\"", re.IGNORECASE
)
_INDENT = "    "


def inject_permissions(text: str) -> tuple[str, list[str]]:
    """Return ``(patched_text, injected_permissions)``; idempotent.

    Only inserts the permissions from :data:`PERMISSIONS` that are not already
    declared, placing them directly after the ``<manifest ...>`` opening tag.
    """
    declared = {match.group(1) for match in _DECLARED_PERMISSION.finditer(text)}
    missing = [permission for permission in PERMISSIONS if permission not in declared]
    if not missing:
        return text, []

    opening_tag = _MANIFEST_OPEN_TAG.search(text)
    if opening_tag is None:
        raise ValueError("manifest has no <manifest ...> opening tag")

    lines = "\n".join(
        f'{_INDENT}<uses-permission android:name="{permission}"/>' for permission in missing
    )
    insert_at = opening_tag.end()
    patched = f"{text[:insert_at]}\n{lines}{text[insert_at:]}"
    return patched, missing


def apply_patch(path: Path) -> list[str]:
    """Patch the manifest at ``path`` in place; return the injected permissions."""
    text = path.read_text(encoding="utf-8")
    patched, injected = inject_permissions(text)
    if injected:
        path.write_text(patched, encoding="utf-8")
    return injected


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Inject RECORD_AUDIO/MODIFY_AUDIO_SETTINGS permissions into the "
        "generated Tauri Android manifest (idempotent)."
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=DEFAULT_MANIFEST,
        help="path to the generated AndroidManifest.xml (default: %(default)s)",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        injected = apply_patch(args.manifest)
    except (OSError, ValueError) as exc:
        print(f"patch-mobile-manifests: {exc}", file=sys.stderr)
        return 1
    if injected:
        for permission in injected:
            print(f"patched {args.manifest}: injected {permission}")
    else:
        print(f"{args.manifest}: audio permissions already declared, nothing to do")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
